<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Datasatuan extends Private_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Tbl_satuan_barang_model');
        $this->load->library('datatables');
    }

    public function index()
    {
        $data = [];
        $data['create_link'] = base_url("barang/satuan/create");

        $this->template->load('template', 'datasatuan/tbl_satuan_barang_list', $data);
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Tbl_satuan_barang_model->json();
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('barang/satuan/do_create'),
            'id' => set_value('id'),
            'nama_satuan' => set_value('nama_satuan'),
        );
        $this->template->load('template', 'datasatuan/tbl_satuan_barang_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'nama_satuan' => $this->input->post('nama_satuan', TRUE),
            );

            if ($this->Tbl_satuan_barang_model->insert($data)) {
                $this->session->set_flashdata('success', "Berhasil membuat data.");
            } else {
                $this->session->set_flashdata('error', "Gagal membuat data. Silakan coba lagi setelah beberapa saat");
            }

            redirect(site_url('barang/satuan'));
        }
    }

    public function update($id)
    {
        $row = $this->Tbl_satuan_barang_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('barang/satuan/do_update'),
                'id' => set_value('id', $row->id),
                'nama_satuan' => set_value('nama_satuan', $row->nama_satuan),
            );
            $this->template->load('template', 'datasatuan/tbl_satuan_barang_form', $data);
        } else {
            $this->session->set_flashdata('error', 'Tidak ada data yang tersedia.');
            redirect(site_url('barang/satuan'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'nama_satuan' => $this->input->post('nama_satuan', TRUE),
            );

            if ($this->Tbl_satuan_barang_model->update($this->input->post('id', TRUE), $data)) {
                $this->session->set_flashdata('success', "Berhasil memperbarui data.");
            } else {
                $this->session->set_flashdata('error', "Gagal memperbarui data.");
            }


            redirect(site_url('barang/satuan'));
        }
    }

    public function delete($id)
    {
        $row = $this->Tbl_satuan_barang_model->get_by_id($id);

        if ($row) {
            if ($this->Tbl_satuan_barang_model->delete($id)) {
                $this->session->set_flashdata('success', "Berhasil menghapus data.");
            } else {
                $this->session->set_flashdata('error', "Gagal menghapus data.");
            }

            redirect(site_url('barang/satuan'));
        } else {
            $this->session->set_flashdata('error', 'Gagal menghapus ');
            redirect(site_url('barang/satuan'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('nama_satuan', 'nama satuan', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Datasatuan.php */
/* Location: ./application/controllers/Datasatuan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-09 11:17:21 */
/* http://harviacode.com */