<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Departemen extends Private_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Tbl_departemen_model');
        $this->load->library('datatables');
    }

    public function index()
    {
        $data = [];
        $data['create_link'] = base_url("departemen/create");
        $this->template->load('template', 'departemen/tbl_departemen_list', $data);
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Tbl_departemen_model->json();
    }


    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('departemen/create_action'),
            'id' => set_value('id'),
            'nama_departemen' => set_value('nama_departemen'),
        );
        $this->template->load('template', 'departemen/tbl_departemen_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'nama_departemen' => $this->input->post('nama_departemen', TRUE),
            );

            if ($this->Tbl_departemen_model->insert($data)) {
                $this->session->set_flashdata('success', "Berhasil membuat data.");
            } else {
                $this->session->set_flashdata('error', "Gagal membuat data. Silakan coba lagi setelah beberapa saat");
            }

            redirect(site_url('departemen'));
        }
    }

    public function update($id)
    {
        $row = $this->Tbl_departemen_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('departemen/update_action'),
                'id' => set_value('id', $row->id),
                'nama_departemen' => set_value('nama_departemen', $row->nama_departemen),
            );
            $this->template->load('template', 'departemen/tbl_departemen_form', $data);
        } else {
            $this->session->set_flashdata('error', 'Tidak ada data yang tersedia.');
            redirect(site_url('departemen'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'nama_departemen' => $this->input->post('nama_departemen', TRUE),
            );

            if ($this->Tbl_departemen_model->update($this->input->post('id', TRUE), $data)) {
                $this->session->set_flashdata('success', "Berhasil memperbarui data.");
            } else {
                $this->session->set_flashdata('error', "Gagal memperbarui data.");
            }

            redirect(site_url('departemen'));
        }
    }

    public function delete($id)
    {
        $row = $this->Tbl_departemen_model->get_by_id($id);

        if ($row) {
            if ($this->Tbl_departemen_model->delete($id)) {
                $this->session->set_flashdata('success', "Berhasil menghapus data.");
            } else {
                $this->session->set_flashdata('error', "Gagal menghapus data.");
            }

            redirect(site_url('departemen'));
        } else {
            $this->session->set_flashdata('error', 'Tidak ada data yang tersedia.');
            redirect(site_url('departemen'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('nama_departemen', 'nama departemen', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Departemen.php */
/* Location: ./application/controllers/Departemen.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-28 15:42:22 */
/* http://harviacode.com */