<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gedung extends Private_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Tbl_gedung_rawat_inap_model');
        $this->load->library('datatables');
    }

    public function index()
    {
        $data = [];
        $data['create_link'] = base_url("gedung/create");
        $this->template->load('template', 'gedung/tbl_gedung_rawat_inap_list', $data);
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Tbl_gedung_rawat_inap_model->json();
    }

    public function ajax_gedung()
    {
        header('Content-Type: application/json');
        echo $this->Tbl_gedung_rawat_inap_model->select2_ajax();
    }


    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('gedung/create_action'),
            'id' => set_value('id'),
            'kode_gedung' => set_value('kode_gedung'),
            'nama_gedung' => set_value('nama_gedung'),
        );
        $this->template->load('template', 'gedung/tbl_gedung_rawat_inap_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $nama_gedung = $this->input->post('nama_gedung', TRUE);
            $kode_gedung = $this->input->post('kode_gedung', TRUE);

            if (preg_match_all('/\b(\w)/', strtoupper($nama_gedung), $m)) {
                $nama_gedung_kode = implode('', $m[1]); // $v is now SOQTU
            }

            $data = array(
                'nama_gedung' => $nama_gedung,
                'kode_gedung' => $kode_gedung
            );

            if ($this->Tbl_gedung_rawat_inap_model->insert($data)) {
                $this->session->set_flashdata('success', "Berhasil membuat data.");
            } else {
                $this->session->set_flashdata('error', "Gagal membuat data. Silakan coba lagi setelah beberapa saat");
            }

            redirect(site_url('gedung'));
        }
    }

    public function update($id)
    {
        $row = $this->Tbl_gedung_rawat_inap_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('gedung/update_action'),
                'id' => set_value('id', $row->id),
                'kode_gedung' => set_value('kode_gedung', $row->kode_gedung),
                'nama_gedung' => set_value('nama_gedung', $row->nama_gedung),
            );
            $this->template->load('template', 'gedung/tbl_gedung_rawat_inap_form', $data);
        } else {
            $this->session->set_flashdata('error', 'Tidak ada data yang tersedia.');
            redirect(site_url('gedung'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('kode_gedung', TRUE));
        } else {
            $data = array(
                'kode_gedung' => $this->input->post('kode_gedung', TRUE),
                'nama_gedung' => $this->input->post('nama_gedung', TRUE),
            );

            if ($this->Tbl_gedung_rawat_inap_model->update($this->input->post('id', TRUE), $data)) {
                $this->session->set_flashdata('success', "Berhasil memperbarui data.");
            } else {
                $this->session->set_flashdata('error', "Gagal memperbarui data.");
            }
            redirect(site_url('gedung'));
        }
    }

    public function delete($id)
    {
        $row = $this->Tbl_gedung_rawat_inap_model->get_by_id($id);

        if ($row) {
            if ($this->Tbl_gedung_rawat_inap_model->delete($id)) {
                $this->session->set_flashdata('success', "Berhasil menghapus data.");
            } else {
                $this->session->set_flashdata('error', "Gagal menghapus data.");
            }

            redirect(site_url('gedung'));
        } else {
            $this->session->set_flashdata('error', 'Tidak ada data yang tersedia.');
            redirect(site_url('gedung'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('nama_gedung', 'nama gedung', 'trim|required');

        $this->form_validation->set_rules('kode_gedung', 'kode_gedung', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Gedung.php */
/* Location: ./application/controllers/Gedung.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-30 19:41:15 */
/* http://harviacode.com */