<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategoribarang extends Private_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Tbl_kategori_barang_model');
        
        $this->load->library('datatables');
    }

    public function index()
    {
        $data = [];
        $data['create_link'] = base_url("barang/kategori/create");
        $data['file_name'] = "LAPORAN KATEGORI BARANG";
        $data['title'] = "LAPORAN KATEGORI BARANG";
        $data['message'] = "";
        $this->template->load('template', 'barang_kategori/tbl_kategori_barang_list', $data);
    }

    public function kategori_json()
    {
        header('Content-Type: application/json');
        echo $this->Tbl_kategori_barang_model->json();
    }

    public function kategori_create()
    {
        $data = array(
            'button' => 'Create',
            'action' => base_url('barang/kategori/do_create'),
            'id' => set_value('id'),
            'id_kelompok' => set_value('id_kelompok'),
            'nama_kategori' => set_value('nama_kategori'),
        );
        $this->template->load('template', 'barang_kategori/tbl_kategori_barang_form', $data);
    }

    public function kategori_create_action()
    {
        $this->kategori_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->kategori_create_action();
        } else {
            $data = array(
                'nama_kategori' => $this->input->post('nama_kategori', TRUE),
                'id_kelompok' => $this->input->post('id_kelompok', TRUE),
            );

            if ($this->Tbl_kategori_barang_model->insert($data)) {
                $this->session->set_flashdata('success', "Berhasil membuat data.");
            } else {
                $this->session->set_flashdata('error', "Gagal membuat data. Silakan coba lagi setelah beberapa saat");
            }
            redirect(site_url('barang/kategori'));
        }
    }

    public function kategori_update($id)
    {
        $row = $this->Tbl_kategori_barang_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => base_url('barang/kategori/do_update'),
                'id' => set_value('id', $row->id),
                'id_kelompok' => set_value('id_kelompok', $row->id_kelompok),
                'nama_kategori' => set_value('nama_kategori', $row->nama_kategori),
            );
            $this->template->load('template', 'barang_kategori/tbl_kategori_barang_form', $data);
        } else {
            $this->session->set_flashdata('error', 'Tidak ada data yang tersedia.');
            redirect(site_url('barang/kategori'));
        }
    }

    public function kategori_update_action()
    {
        $this->kategori_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->kategori_update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'nama_kategori' => $this->input->post('nama_kategori', TRUE),
                'id_kelompok' => $this->input->post('id_kelompok', TRUE),
            );

            if ($this->Tbl_kategori_barang_model->update($this->input->post('id', TRUE), $data)) {
                $this->session->set_flashdata('success', "Berhasil memperbarui data.");
            } else {
                $this->session->set_flashdata('error', "Gagal memperbarui data.");
            }

            redirect(site_url('barang/kategori'));
        }
    }

    public function kategori_delete($id)
    {
        $row = $this->Tbl_kategori_barang_model->get_by_id($id);

        if ($row) {
            if ($this->Tbl_kategori_barang_model->delete($id)) {
                $this->session->set_flashdata('success', "Berhasil menghapus data.");
            } else {
                $this->session->set_flashdata('error', "Gagal menghapus data.");
            }
            redirect(site_url('barang/kategori'));
        } else {
            $this->session->set_flashdata('error', 'Tidak ada data yang tersedia.');
            redirect(site_url('barang/kategori'));
        }
    }

    public function kategori_rules()
    {
        $this->form_validation->set_rules('nama_kategori', 'nama kategori', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Kategoribarang.php */
/* Location: ./application/controllers/Kategoribarang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-09 11:12:11 */
/* http://harviacode.com */