<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelompokbarang extends Private_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model(['Barang_kelompok_model'=>'kelompok']);
        
        $this->load->library('datatables');
    }

    public function index()
    {
        $data = [];
        $data['create_link'] = base_url("barang/kelompok/create");
        $data['file_name'] = "LAPORAN KELOMPOK BARANG";
        $data['title'] = "LAPORAN KELOMPOK BARANG";
        $data['message'] = "";
        $this->template->load('template', 'barang_kelompok/barang_kelompok_list', $data);
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->kelompok->json();
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => base_url('barang/kelompok/do_create'),
            'id' => set_value('id'),
            'nama_kelompok' => set_value('nama_kelompok'),
        );
        $this->template->load('template', 'barang_kelompok/barang_kelompok_form', $data);
    }

    public function create_action()
    {
        $this->rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create_action();
        } else {
            $data = array(
                'nama_kelompok' => $this->input->post('nama_kelompok', TRUE),
            );

            if ($this->kelompok->insert($data)) {
                $this->session->set_flashdata('success', "Berhasil membuat data.");
            } else {
                $this->session->set_flashdata('error', "Gagal membuat data. Silakan coba lagi setelah beberapa saat");
            }
            redirect(site_url('barang/kelompok'));
        }
    }

    public function update($id)
    {
        $row = $this->kelompok->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => base_url('barang/kelompok/do_update'),
                'id' => set_value('id', $row->id),
                'nama_kelompok' => set_value('nama_kelompok', $row->nama_kelompok),
            );
            $this->template->load('template', 'barang_kelompok/barang_kelompok_form', $data);
        } else {
            $this->session->set_flashdata('error', 'Tidak ada data yang tersedia.');
            redirect(site_url('barang/kelompok'));
        }
    }

    public function update_action()
    {
        $this->rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'nama_kelompok' => $this->input->post('nama_kelompok', TRUE),
            );

            if ($this->kelompok->update($this->input->post('id', TRUE), $data)) {
                $this->session->set_flashdata('success', "Berhasil memperbarui data.");
            } else {
                $this->session->set_flashdata('error', "Gagal memperbarui data.");
            }

            redirect(site_url('barang/kelompok'));
        }
    }

    public function delete($id)
    {
        $row = $this->kelompok->get_by_id($id);

        if ($row) {
            if ($this->kelompok->delete($id)) {
                $this->session->set_flashdata('success', "Berhasil menghapus data.");
            } else {
                $this->session->set_flashdata('error', "Gagal menghapus data.");
            }
            redirect(site_url('barang/kelompok'));
        } else {
            $this->session->set_flashdata('error', 'Tidak ada data yang tersedia.');
            redirect(site_url('barang/kelompok'));
        }
    }

    public function rules()
    {
        $this->form_validation->set_rules('nama_kelompok', 'nama kategori', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Kategoribarang.php */
/* Location: ./application/controllers/Kategoribarang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-09 11:12:11 */
/* http://harviacode.com */