<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_pengadaan_obat_alkes_bhp_model extends CI_Model
{

    public $table = 'tbl_barang_pengadaan';
    public $id = 'id';
    public $pk = 'tbl_barang_pengadaan.id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('id_supplier', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('tbl_barang_pengadaan.id', $q);
        $this->db->or_like('tbl_barang_pengadaan.tanggal', $q);
        $this->db->or_like('tbl_barang_pengadaan.id_supplier', $q);
        $this->db->join('tbl_barang_supplier', 'tbl_barang_supplier.id=tbl_barang_pengadaan.id_supplier');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function json()
    {
        $actions = "
        <div class=\"btn-group\" role=\"group\">
            <a href=\"" . site_url('pengadaan/detail/$1') . "\" class=\"btn btn-primary\"><i class=\"fa fa-list\"></i>&nbsp;Rincian</a>
            <a href=\"" . site_url('pengadaan/update/$1') . "\" class=\"btn btn-default\"><i class=\"fa fa-pen\"></i> Edit</a>
            <a href=\"" . site_url('pengadaan/delete/$1') . "\" class=\"btn btn-danger\" onclick=\"javascript: return confirm('Apakah Anda yakin?')\"><i class=\"fa fa-trash-alt\"></i> Hapus</a>
        </div>
        ";

        $this->datatables->select("tbl_barang_supplier.id as id_supplier, {$this->pk}, tbl_barang_pengadaan.tanggal, no_faktur, nama_supplier");
        $this->datatables->from($this->table);

        $this->datatables->join('tbl_barang_supplier', 'tbl_barang_supplier.id=tbl_barang_pengadaan.id_supplier');

        $this->datatables->add_column('action', $actions, 'id');

        return $this->datatables->generate();
    }

    // insert data
    function insert($data)
    {
        $result = $this->db->insert($this->table, stamp($data));

        if (!$result) return false;

        $insert_id = $this->db->insert_id();

        return  $insert_id;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, stamp($data));
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->delete($this->table);
    }

    public function detail_datatables($id)
    {
        $actions = "
        <div class=\"btn-group\" role=\"group\">
            <a href=\"" . site_url('pengadaan/detail_do_delete/$1') . "\" class=\"btn btn-sm btn-danger\" onclick=\"javascript: return confirm('Apakah Anda yakin?')\"><i class=\"fa fa-trash-alt\"></i> Hapus</a>
        </div>
        ";

        $this->datatables->select("tbl_barang_pengadaan_detail.id, no_faktur, nama_barang, qty, tbl_barang.harga");
        $this->datatables->from("tbl_barang_pengadaan_detail");
        $this->datatables->where("id_barang_pengadaan", $id);
        $this->datatables->join("tbl_barang_pengadaan", "tbl_barang_pengadaan.id = tbl_barang_pengadaan_detail.id_barang_pengadaan");
        $this->datatables->join("tbl_barang", "tbl_barang.id = tbl_barang_pengadaan_detail.id_barang");
        $this->datatables->add_column("action", $actions, 'id');

        return $this->datatables->generate();
    }

    public function get_detail($id)
    {
        $this->db->where("id_barang_pengadaan", $id);
        return $this->db->get("tbl_barang_pengadaan_detail")->row();
    }


    public function get_detail_item($id)
    {
        $this->db->where("id", $id);
        return $this->db->get("tbl_barang_pengadaan_detail")->row();
    }

    public function detail_insert($data)
    {
        return $this->db->insert("tbl_barang_pengadaan_detail", stamp($data));
    }

    function detail_delete($id)
    {
        $this->db->where("id", $id);
        return $this->db->delete("tbl_barang_pengadaan_detail");
    }
}

/* End of file Tbl_pengadaan_obat_alkes_bhp_model.php */
/* Location: ./application/models/Tbl_pengadaan_obat_alkes_bhp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-10 02:07:42 */
/* http://harviacode.com */