<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_gedung_rawat_inap_model extends CI_Model
{

    public $table = 'tbl_rs_gedung';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id, kode_gedung, nama_gedung');
        $this->datatables->from('tbl_rs_gedung');

        $actions = "
        <div class=\"btn-group\" role=\"group\">
            <a href=\"".site_url('gedung/update/$1')."\" class=\"btn btn-default\"><i class=\"fa fa-pen\"></i> Edit</a>
            <a href=\"".site_url('gedung/delete/$1')."\" class=\"btn btn-danger\" onclick=\"javascript: return confirm('Apakah Anda yakin?')\"><i class=\"fa fa-trash-alt\"></i> Hapus</a>
        </div>
        ";

        $this->datatables->add_column('action', $actions, 'id');

        return $this->datatables->generate();
    }

    function select2_ajax() {
        $this->ajax->select('id, nama_gedung');
        $this->ajax->from('tbl_rs_gedung');

        return $this->ajax->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        return $this->db->insert($this->table, stamp($data));
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, stamp($data));
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->delete($this->table);

    }
}

/* End of file Tbl_gedung_rawat_inap_model.php */
/* Location: ./application/models/Tbl_gedung_rawat_inap_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-30 19:41:15 */
/* http://harviacode.com */