<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_dokter_model extends CI_Model
{

    public $table = 'tbl_dokter';
    public $id = 'id';
    public $pk = "tbl_dokter.id";
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select("{$this->pk},nama_dokter,no_telepon,nama_spesialis,no_izin_praktik,alumni");
        $this->datatables->from('tbl_dokter');
        //add this line for join
        $this->datatables->join('tbl_dokter_spesialis', 'tbl_dokter.id_spesialis = tbl_dokter_spesialis.id');
        $this->datatables->add_column('action', 
        anchor(site_url('dokter/make_user/$1'),'<i class="fa fa-user" aria-hidden="true"></i>', array('class' => 'btn btn-primary btn-sm'))."&nbsp;".
        anchor(site_url('dokter/update/$1'),'<i class="fa fa-pen" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-sm'))."&nbsp;".
        anchor(site_url('dokter/delete/$1'),'<i class="fa fa-trash-alt" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Apakah Anda yakin?\')"'), 'id');
        return $this->datatables->generate();
    }

    function select2_ajax() {
        $id_dokter = $this->input->post("id_dokter", true);

        $this->ajax->select('id, kode_dokter, nama_dokter');
        $this->ajax->from($this->table);

        if(!empty($id_dokter)) $this->ajax->where("$this->id = $id_dokter");

        $this->ajax->searchable_column(["nama_dokter"]);

        return $this->ajax->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_by_id_array($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row_array();
    }

    // insert data
    function insert($data)
    {
        return $this->db->insert($this->table, stamp($data));
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, stamp($data));
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->delete($this->table);

    }

}

/* End of file Tbl_dokter_model.php */
/* Location: ./application/models/Tbl_dokter_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-27 18:45:56 */
/* http://harviacode.com */