<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_jadwal_praktek_dokter_model extends CI_Model
{

    public $table = 'tbl_dokter_jadwal';
    public $id = 'id';
    public $pk = 'tbl_dokter_jadwal.id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get($term, $id_poli = "", $limit = 10, $hari_ini = false)
    {
        $this->db->select("{$this->pk}, *, CONVERT (jam_mulai, time) as jam_mulai,CONVERT (jam_selesai, time) as jam_selesai");
        $this->db->join("tbl_dokter", "tbl_dokter.id_dokter = tbl_dokter_jadwal.id_dokter");
        $this->db->join("tbl_poliklinik", "tbl_poliklinik.id_poliklinik = tbl_dokter_jadwal.id_poliklinik");

        $this->db->like(["nama_dokter" => $term]);

        if (!empty($id_poli)) $this->db->where([
            "tbl_dokter_jadwal.id_poliklinik" => $id_poli,
        ]);

        if ($hari_ini) $this->db->where([
            "tbl_dokter_jadwal.hari" => $hari_ini,
        ]);

        $this->db->limit($limit);

        $result = $this->db->get($this->table)->result();

        foreach ($result as $item) {
            $start = strtotime($item->jam_mulai);
            $end = strtotime($item->jam_selesai);

            if (time() >= $start && time() <= $end) {
                $item->tersedia = true;
            } else {
                $item->tersedia = false;
            }
        }

        return $result;
    }

    // datatables
    function json()
    {
        $this->datatables->select("{$this->pk}, id_dokter, CONCAT(id_dokter, '_', kode_dokter ,nama_dokter) as nama_dokter,hari, CONVERT (jam_mulai, time) as jam_mulai,CONVERT (jam_selesai, time) as jam_selesai,nama_poliklinik");
        $this->datatables->from('tbl_dokter_jadwal');
        //add this line for join
        $this->datatables->join('tbl_dokter', 'tbl_dokter_jadwal.id_dokter = tbl_dokter.id');
        $this->datatables->join('tbl_poliklinik', 'tbl_dokter_jadwal.id_poliklinik = tbl_poliklinik.id');
        $this->datatables->add_column('action', anchor(site_url('jadwalpraktek/update/$1'), '<i class="fa fa-pen" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . " 
                " . anchor(site_url('jadwalpraktek/delete/$1'), '<i class="fa fa-trash-alt" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Apakah Anda yakin?\')"'), 'id');
        return $this->datatables->generate();
    }

    function jadwal_all()
    {
        $id_poli = $this->input->post("id_poli", true);

        if (!empty($id_poli)) $this->ajax->where("tbl_dokter_jadwal.id_poliklinik", $id_poli);

        return $this->ajax->select("{$this->pk}, id_dokter, kode_dokter, nama_dokter, hari, CONVERT (jam_mulai, time) as jam_mulai,CONVERT (jam_selesai, time) as jam_selesai,nama_poliklinik")
            ->from($this->table)
            ->join('tbl_dokter', 'tbl_dokter_jadwal.id_dokter = tbl_dokter.id')
            ->join('tbl_poliklinik', 'tbl_dokter_jadwal.id_poliklinik = tbl_poliklinik.id')
            ->searchable_column(["nama_dokter"])
            ->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select("{$this->pk}, id_poliklinik, id_dokter, hari, CONVERT (jam_mulai, time) as jam_mulai,CONVERT (jam_selesai, time) as jam_selesai");
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        return $this->db->insert($this->table, stamp($data));
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, stamp($data));
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->delete($this->table);
    }
}

/* End of file Tbl_jadwal_praktek_dokter_model.php */
/* Location: ./application/models/Tbl_jadwal_praktek_dokter_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-27 19:23:29 */
/* http://harviacode.com */