<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_kategori_tindakan_model extends CI_Model
{

    public $table = 'tbl_tindakan_kategori';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,kode_kategori_tindakan,kategori_tindakan');
        $this->datatables->from('tbl_tindakan_kategori');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_tindakan_kategori.field = table2.field');
        $this->datatables->add_column('action',anchor(site_url('kategoritindakan/update/$1'),'<i class="fa fa-pen" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('kategoritindakan/delete/$1'),'<i class="fa fa-trash-alt" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Apakah Anda yakin?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        return $this->db->insert($this->table, stamp($data));
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, stamp($data));
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->delete($this->table);

    }

}

/* End of file Tbl_kategori_tindakan_model.php */
/* Location: ./application/models/Tbl_kategori_tindakan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-16 17:44:43 */
/* http://harviacode.com */