<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_penjualan_obat_alkes_bhp_model extends CI_Model
{

    public $table = 'tbl_penjualan_obat_alkes_bhp';
    public $id = 'no_faktur';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function json() {
        $actions = "
        <div class=\"btn-group\" role=\"group\">
            <a href=\"".site_url('penjualan/delete/$1')."\" class=\"btn btn-danger\" onclick=\"javascript: return confirm('Apakah Anda yakin?')\"><i class=\"fa fa-trash-alt\"></i> Hapus</a>
        </div>
        ";

        $this->datatables->select("no_faktur, tanggal");
        $this->datatables->from($this->table);

        $this->datatables->add_column('action', $actions, 'no_faktur');

        return $this->datatables->generate();
    }


    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_faktur', $q);
	$this->db->or_like('tanggal', $q);
	
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('tbl_penjualan_obat_alkes_bhp.no_faktur', $q);
	$this->db->or_like('tbl_penjualan_obat_alkes_bhp.tanggal', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        return $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->delete($this->table);

    }

}

/* End of file Tbl_penjualan_obat_alkes_bhp_model.php */
/* Location: ./application/models/Tbl_penjualan_obat_alkes_bhp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-10 02:07:42 */
/* http://harviacode.com */