<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_pegawai_model extends CI_Model
{

    public $table = 'tbl_pegawai';
    public $id = 'nik';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('nik,nama_pegawai,npwp,nama_jabatan,nama_jenjang,nama_departemen,nama_bidang');
        $this->datatables->from('tbl_pegawai');
        //add this line for join
        $this->datatables->join('tbl_jabatan', 'tbl_pegawai.id_jabatan = tbl_jabatan.id_jabatan');
        $this->datatables->join('tbl_jenjang', 'tbl_pegawai.kode_jenjang = tbl_jenjang.kode_jenjang');
        $this->datatables->join('tbl_departemen', 'tbl_pegawai.id_departemen = tbl_departemen.id_departemen');
        $this->datatables->join('tbl_bidang', 'tbl_pegawai.id_bidang = tbl_bidang.id_bidang');
        $this->datatables->add_column('action', "$2 $3" .
            anchor(site_url('pegawai/update/$1'), '<i class="fa fa-pen" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm')) . "&nbsp;" .
            anchor(site_url('pegawai/delete/$1'), '<i class="fa fa-trash-alt" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Apakah Anda yakin?\')"'), 'nik, make_apoteker(nama_jabatan, nik), make_keuangan(nama_departemen, nik)');
        return $this->datatables->generate();
    }

    function get($id = "", $q = "", $limit = 10, $start = 0)
    {
        $this->db->order_by($this->id, $this->order);

        $this->db->where($this->id, $id);

        if (!empty($q)) {
            $this->db->like('nik', $q);
            $this->db->or_like('nama_pegawai', $q);
            $this->db->or_like('jenis_kelamin', $q);
            $this->db->or_like('npwp', $q);
            $this->db->or_like('id_jenjang_pendidikan', $q);
            $this->db->or_like('tempat_lahir', $q);
            $this->db->or_like('tanggal_lahir', $q);
            $this->db->or_like('id_jabatan', $q);
            $this->db->or_like('kode_jenjang', $q);
            $this->db->or_like('id_departemen', $q);
            $this->db->or_like('id_bidang', $q);
        }

        $this->db->limit($limit, $start);
        return $this->db->get($this->table);
    }

    // get all
    function get_all()
    {
        return $this->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        return $this->get($id)->row();
    }

    // get data by id
    function get_by_id_array($id)
    {
        return $this->get($id)->row_array();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        return $this->get("", $q)->num_rows();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        return $this->get("", $q, $limit, $start)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Tbl_pegawai_model.php */
/* Location: ./application/models/Tbl_pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-28 16:16:01 */
/* http://harviacode.com */