<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_supplier_model extends CI_Model
{

    public $table = 'tbl_barang_supplier';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function select2_ajax() {
        $id_supplier = $this->input->post('id_supplier');

        if(!empty($id_supplier)) $this->ajax->where("id", $id_supplier);

        return $this->ajax->select('id, kode_supplier, nama_supplier, alamat')
                          ->from($this->table)
                          ->limit(5)
                          ->searchable_column(['nama_supplier'])
                          ->generate();
    }

    // datatables
    function json() {
        $this->datatables->select('id,kode_supplier,nama_supplier,alamat,no_telpon');
        $this->datatables->from('tbl_barang_supplier');
        $this->datatables->add_column('action',anchor(site_url('barang/supplier/$1/update'),'<i class="fa fa-pen" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('barang/supplier/$1/delete'),'<i class="fa fa-trash-alt" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Apakah Anda yakin?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        return $this->db->insert($this->table, stamp($data));
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, stamp($data));
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->delete($this->table);

    }

}

/* End of file Tbl_supplier_model.php */
/* Location: ./application/models/Tbl_supplier_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-11 17:19:48 */
/* http://harviacode.com */